### ISSUE TITLE
Goggle Diving Helmet Crashes when trying to craft

### ISSUE THREAD

**Issue by DragonGirl7567** [Robocraft999/CreatePlus#28] opened 2022-09-03 03:48 UTC
when trying to craft the goggle diving helmet, the game crashes

**Steps:**
1. have the diving helmet and goggle ready in the inventory
2. place them into crafting slots (inventory or crafting

**_The game crashes and says in the launcher (when it relaunches):_**
The game crashed whilst exception in server tick loop Error: java.lang.NoSuchFieldError: DIVING_HELMET

Minecraft: 1.18.2
Create: create-1.18.2-0.5.0.d.jar
Create Plus: createplus-1.18.2_v0.5.1.jar
Flywheel: flywheel-forge-1.18.2-0.6.5.jar

**Comment by Robocraft999** [comment] 2022-09-04 07:18
duplicate of #27

**Closed as completed** 2022-09-04 07:21 UTC
